In [1]:
!pip install numpy

In [4]:
import numpy as np
stock_prices = np.random.randint(100, 501, size=(30, 5))
average_prices = stock_prices.mean(axis=0)
print(f"Average stock prices: {average_prices}")
max_price = stock_prices.max() 
max_price_indices = np.where(stock_prices == max_price)
max_price_day = max_price_indices[0][0] + 1
max_price_company = max_price_indices[1][0] + 1  
print(f"Highest price recorded: {max_price} at Day {max_price_day}, Company {max_price_company}")
min_prices = stock_prices.min(axis=0)
max_prices = stock_prices.max(axis=0)
normalized_prices = (stock_prices - min_prices) / (max_prices - min_prices)
print("Normalized prices:")
print(normalized_prices)
print("Risky Investment Days:")
for day in range(stock_prices.shape[0]):
    risky_stocks = stock_prices[day] < 200 
    if np.any(risky_stocks):
        print(f"Day {day + 1}: {stock_prices[day][risky_stocks]}")



Average stock prices: [291.83333333 292.43333333 317.96666667 256.56666667 277.13333333]
Highest price recorded: 497 at Day 8, Company 5
Normalized prices:
[[0.96111111 0.31842105 0.97179487 0.44041451 0.        ]
 [0.77222222 0.36315789 0.86153846 0.         0.66246851]
 [0.03055556 0.81842105 0.36666667 0.37046632 0.67002519]
 [0.21111111 0.73947368 0.26923077 0.73056995 0.08312343]
 [0.14722222 0.20789474 0.95641026 0.26683938 0.12846348]
 [0.48888889 0.29210526 0.39487179 0.74352332 0.56675063]
 [0.05       0.38947368 0.99487179 0.11658031 0.40302267]
 [0.43888889 0.35789474 0.38205128 0.25647668 1.        ]
 [0.01666667 1.         0.39230769 0.18134715 0.46347607]
 [0.53611111 0.08684211 0.17435897 0.95595855 0.62468514]
 [0.16388889 0.70526316 0.11538462 0.19948187 0.63476071]
 [0.49166667 0.67894737 0.         0.83678756 0.80856423]
 [0.43888889 0.57631579 0.96666667 0.06994819 0.49118388]
 [0.71944444 0.24736842 0.15128205 0.53108808 0.35012594]
 [0.4        0.65       0.910256

In [4]:
import numpy as np
resources = np.array([
    [15, 40, 32],  
    [20, 42, 35],  
    [25, 38, 30],  
    [18, 50, 40],
    [22, 37, 36],  
    [28, 45, 33]  
])
total_resources = resources.sum(axis=0) 
total_oxygen, total_water, total_food = total_resources
print(f"Total resources needed (tons): Oxygen: {total_oxygen}, Water: {total_water}, Food: {total_food}")
monthly_max_idx = np.argmax(resources, axis=1) 
resources_names = ['Oxygen', 'Water', 'Food']
monthly_max_resources = [resources_names[idx] for idx in monthly_max_idx]
monthly_max_values = resources.max(axis=1)
highest_month = np.argmax(monthly_max_values)
highest_resource = monthly_max_resources[highest_month]
highest_value = monthly_max_values[highest_month]
print(f"Highest consumption in a month: {highest_resource} ({highest_value} tons in month {highest_month})")
std_devs = resources.std(axis=0)
std_oxygen, std_water, std_food = std_devs
print(f"Standard deviation of consumption: Oxygen: {std_oxygen:.1f}, Water: {std_water:.1f}, Food: {std_food:.1f}")
transposed_resources = resources.T
print("Transposed matrix:")
print(transposed_resources)


Total resources needed (tons): Oxygen: 128, Water: 252, Food: 206
Highest consumption in a month: Water (50 tons in month 3)
Standard deviation of consumption: Oxygen: 4.3, Water: 4.4, Food: 3.2
Transposed matrix:
[[15 20 25 18 22 28]
 [40 42 38 50 37 45]
 [32 35 30 40 36 33]]


In [5]:
import numpy as np
points = np.array([
    [10, 25, 30, 22, 12, 18, 26, 32, 24, 29], 
    [20, 15, 12, 28, 24, 26, 30, 18, 22, 25],  
    [35, 30, 32, 40, 28, 34, 29, 31, 26, 37], 
    [12, 18, 20, 15, 22, 14, 19, 21, 23, 17], 
    [28, 26, 27, 25, 30, 29, 35, 32, 31, 38] 
])
average_points = points.mean(axis=1) 
print("Average points per game:")
print(average_points)
total_points = points.sum(axis=1)  
best_player_idx = np.argmax(total_points) 
worst_player_idx = np.argmin(total_points)
print(f"Best-performing player: Player {best_player_idx + 1} (Total: {total_points[best_player_idx]} points)")
print(f"Worst-performing player: Player {worst_player_idx + 1} (Total: {total_points[worst_player_idx]} points)")
mask = points > 30 
for i in range(points.shape[0]): 
    games_above_30 = np.where(mask[i])[0] + 1 
    print(f"Player {i+1}: Games {games_above_30}")


Average points per game:
[22.8 22.  32.2 18.1 30.1]
Best-performing player: Player 3 (Total: 322 points)
Worst-performing player: Player 4 (Total: 181 points)
Player 1: Games [8]
Player 2: Games []
Player 3: Games [ 1  3  4  6  8 10]
Player 4: Games []
Player 5: Games [ 7  8  9 10]
